CREATE TABLE `S_VOUCHERS` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '代金卷ID',
  `GYS_ID` bigint(20) DEFAULT NULL COMMENT '供应商ID',
  `GYS_NAME` varchar(100) DEFAULT NULL COMMENT '供应商名称',
  `AMOUNT` int(11) DEFAULT NULL COMMENT '代金卷金额',
  `USE_SCOPE` int(11) DEFAULT NULL COMMENT '使用金额范围',
  `NUM` int(11) DEFAULT NULL COMMENT '发行数量(-1:无限量)',
  `ITEM_TYPE` varchar(2) DEFAULT NULL COMMENT '商品范围类型(1:全部 2:商品大类 3:商品)',
  `ITEMS` varchar(100) DEFAULT NULL COMMENT '商品范围(包含类别和指定商品)',
  `RANGE_CODE` varchar(2) DEFAULT NULL COMMENT '适用范围(1:全平台 2:指定成员)',
  `STATUS` varchar(2) DEFAULT NULL COMMENT '代金卷状态(1:启用 2:编辑 3：锁定 4:删除)',
  `GMT_START_TIME` datetime DEFAULT NULL COMMENT '开发时间',
  `GMT_END_TIME` datetime DEFAULT NULL COMMENT '结束时间',
  `GMT_CREATE_TIME` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `GMT_UPDATE_TIME` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '修改时间',
  `REMARKS` varchar(1000) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`ID`) COMMENT '主键',
  UNIQUE KEY `ID_UNIQUE` (`ID`) COMMENT '主键唯一标识'
) ENGINE=InnoDB AUTO_INCREMENT=10000044 DEFAULT CHARSET=utf8